// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4YvUXCPrHoieVMjBF4U4bPwTJFhfRqQM',
    appId: '1:462977223945:web:feb3b8a537d0a4eb22d7d8',
    messagingSenderId: '462977223945',
    projectId: 'classhub-app',
    authDomain: 'classhub-app.firebaseapp.com',
    storageBucket: 'classhub-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5N75DOA3Uf2qVWUWZVOQSOHw8qX9ARk',
    appId: '1:462977223945:android:ffe03cdc32b9fd6322d7d8',
    messagingSenderId: '462977223945',
    projectId: 'classhub-app',
    storageBucket: 'classhub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6SrRhGRHIVOpvxv7ZAVzJdoeZeGL-lc',
    appId: '1:462977223945:ios:df705831329d43b622d7d8',
    messagingSenderId: '462977223945',
    projectId: 'classhub-app',
    storageBucket: 'classhub-app.firebasestorage.app',
    iosBundleId: 'com.example.classhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6SrRhGRHIVOpvxv7ZAVzJdoeZeGL-lc',
    appId: '1:462977223945:ios:df705831329d43b622d7d8',
    messagingSenderId: '462977223945',
    projectId: 'classhub-app',
    storageBucket: 'classhub-app.firebasestorage.app',
    iosBundleId: 'com.example.classhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4YvUXCPrHoieVMjBF4U4bPwTJFhfRqQM',
    appId: '1:462977223945:web:4f13fa814dca187322d7d8',
    messagingSenderId: '462977223945',
    projectId: 'classhub-app',
    authDomain: 'classhub-app.firebaseapp.com',
    storageBucket: 'classhub-app.firebasestorage.app',
  );
}
